name: Package Application with Pyinstaller

on: 
  push:
    tags:
    - '*'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./
        
    - name: Package Application linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: ./
        
    - name: Rename Files
      run: |
        mv "dist/windows/log4shell-detector.exe" "dist/windows/log4shell-detector-win.exe"
        mv "dist/linux/log4shell-detector" "dist/windows/win-log4shell-detector-lin"
        
    - uses: ncipollo/release-action@v1.9.0
      with:
        artifacts: "dist/windows/*.exe,dist/linux/*"
        token: ${{ secrets.GITHUB_TOKEN }}
